### ISSUE TITLE
add integration for puppet-repl

### ISSUE THREAD

**Issue by igalic** [voxpupuli/puppet-mode#68]
I've opened this issue already with the https://github.com/nwops/puppet-repl/issues/22 project, but perhaps it's more suited here.

We should add a repl mode, which allows us to send regions or buffers to a repl (and evaluate them there)

**Comment by lunaryorn** [comment]
I'd welcome pull requests, but I'm not using Puppet anymore, and am not really maintaining this mode anymore.

**Comment by igalic** [comment]
@lunaryorn have you considered moving this project over to @voxpupuli then?
We already have vim-puppet there, so it would be in good company.

**Comment by lunaryorn** [comment]
@igalic What's @voxpupuli?

**Comment by igalic** [comment]
@lunaryorn from https://voxpupuli.org/
> We are a collective of Puppet module, tooling and documentation authors all working together to ensure continued development on the code we maintain.
> 
> We work under a shared name and namespace and synchronize our efforts. Having no official relation to Puppet Inc. allows us to maintain our own pace and direction when it comes to how we work and develop. However, all community members are welcome and this includes many Puppet Labs employees.

**Comment by bbatsov** [comment]
I'd rather us not do this.

**Comment by lunaryorn** [comment]
@bbatsov Why's that?  I see not much point in this mode being under my name… I'm not properly maintaining it anymore.

I won't move without your consent though, for sure.

**Comment by bbatsov** [comment]
Don't see a strong focus on editor support there and I doubt moving it there would solicit contributors either. I still have some stake in puppet usage, so I'm not really willing to give up having control over the package.

**Comment by igalic** [comment]
this isn't about giving up control
all contributors here would become contributors to @voxpupuli
conversly, all @voxpupuli contributors would become contributors of puppet-mode

**Comment by lunaryorn** [comment]
@bbatsov I pinged you on Gitter, let's discuss privately, ok?

@igalic Would we become members of the organisation, or merely external contributors to the repo?  How is the organisation governed?  Who'd have the authority to make decisions about this package if it were moved into the org?

**Comment by bbriggs** [comment]
Hello all!

I'm one of the members of the Project Management Committee (PMC) elected to help govern VP. I'd like to address any questions or concerns you have about continued module maintenance and transferring the module to VP namespace. 

Our mission at VP is to make sure good projects like this don't fall by the wayside, which is why @igalic kindly offered to add this to the list of things we maintain. We are a fairly large and active group (over 70 members) and ensure all our modules are maintained and development continues.

Historically, we offer membership to those who donate modules or tools to the VP organization. Sometimes people wish to join and sometimes they are happy to simply know their baby is being taken care of. Membership is offered but not required of anyone. Additionally, you may step down at any time. Furthermore, as @igalic stated, all contributors here would become VP contributors and vice versa. We take a 'collective' approach to module maintenance. 

Is there any way I can further help you work through your consideration?

**Comment by lunaryorn** [comment]
@bbriggs Thanks for joining and explaining. We'll consider moving.

**Comment by igalic** [comment]
this still needs a fix in README.md (and a release i guess)

**Comment by paran1** [comment]
Mention of the puppet-debugger integration was added to README.md in 03f608234ed0cf403966454de6758ec7fc9c784d, so I think this issue could be closed.
