### ISSUE TITLE
Move to voxpupuli org

### ISSUE THREAD

**Issue by lunaryorn** [voxpupuli/puppet-mode#73]
Given that I'm essentially not maintaining this repository anymore, and don't intend to spent any further time on it, I'd like to move it over to @voxpupuli as suggested in #68.

@bbatsov and me discussed privately, and we agreed, provided that the merge retains admin access to the repository for @bbatsov and involves him in the decision making process for changes to the repository.  As far as I'm concerned, I'd prefer to be removed, as I don't intend to work on this mode anymore.

@igalic @bbriggs  Could you perhaps outline how the move would look like?

# TODO

- [x] Clarify status of @bbatsov if the repo was moved.

**Comment by bbriggs** [comment]
No problem. 

Here is the documented procedure on migrating your module to VP: https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli

**Comment by bbriggs** [comment]
Granted, this is very specific to a puppet module, but the essence is the same.

**Comment by lunaryorn** [comment]
@bbriggs I must admit that I'm unsure and could really use someone to talk me through the process.  Most of the site you've linked to talks about specifics of puppetforge releases which obviously don't apply to this repo, so I'm unsure what's actually relevant.

I've transferred Emacs packages across different user accounts before, so as far as the packaging/deployment side (e.g. MELPA, etc.) is concerned I know what to do for MELPA to pick up the new package, but I'm not really sure about the onboarding process for Vox Populi.

Could you help me on that?

**Comment by bbriggs** [comment]
You're absolutely right, we typically deal with Puppet modules. We do maintain a few other tools related to the puppet ecosystem that aren't modules (see [here](https://github.com/voxpupuli/modulesync) as one example). 

In this case, I would grab one of our members who has more experience with MELPA than I do and we will all walk through it together. 

Since you're already familiar with the MELPA process, I'll just discuss how we'll move this to VP.

1. We will add you to the modules/admin team which will allow you to transfer a repo into our org and have write access to it immediately after.
1. Disable all your webhooks except Travis (if any exist)
1. From there, we will start the MELPA transfer process of updating metadata, bumping version, and publishing the new one from our source.
1. Welcome to Vox Pupuli! We absolutely welcome to you stay and join us as a permanent contributor.

The rest of the stuff referring to modulesync applies specifically to modules, so we won't worry about that here.

**Comment by bbriggs** [comment]
To smooth the transition, why not join us on Freenode IRC in #voxpupuli to coordinate the work? 

My nick is `fraq`. If you just drop in and mention who you are and what you're there to do, someone will help you in short order :)

cc @bastelfreak since he never sleeps and will probably be the first to help

**Comment by lunaryorn** [comment]
uh, uhm, IRC… didn't do that since years :blush:  I'll join tonight, ok?

**Comment by lunaryorn** [comment]
Though I must admit that I prefer Github issues for this kind of thing, simply because they are asynchronous and work better over different time zones, etc.  I'm not from the states after all :)

**Comment by bastelfreak** [comment]
We're available 24/7 in #voxpupuli, so this should be fine to discuss things.

**Comment by bbriggs** [comment]
In the meantime, I'll go ahead and grant you access to the right group so you can transfer on over when you're ready :)

**Comment by lunaryorn** [comment]
@bbriggs Thanks a lot!  Would you mind to invite @bbatsov as well?  He's also a maintainer of this repo…

**Comment by bbriggs** [comment]
Sorry I didn't see this sooner. Yeah, I'll add them as well.

**Comment by lunaryorn** [comment]
It's been moved; MELPA PR at https://github.com/melpa/melpa/pull/4338.

I updated links throughout the repo as well, so should be good to go.

**Comment by lunaryorn** [comment]
I've left the organisation again, and stopped watching this repository.  If you need any further from me, please mention me.

**Comment by bbriggs** [comment]
Thank you for your contribution!

**Comment by lunaryorn** [comment]
@bbriggs You're welcome; many thanks for taking over, you're taking a huge burden from my shoulders :blush:  I'm very grateful for your help.

**Comment by rski** [comment]
@bbatsov everything ok? You should have proper contributor access now

**Comment by bbatsov** [comment]
Yeah, I got an invite.

**Comment by igalic** [comment]
\o/ welcome, welcome! \o/
